version: 2   # aqui es de donde sacara los datos

sources:
  - name: raw
    schema: stackoverflow #Dataset name - BigQuery, tiene q ser el mismo nombre q hay en BQ
    tables:
      - name: badges   # nombres de los datasets en bq, si se añade una nueva en bq, hay que referenciarlo aquí para poder usarlo.
      - name: posts_answers
      - name: posts_questions
      - name: users
