version: 2   # la configuración para los 4 modelos que se encuentran dentro de esta carpeta staging, y las pruebas de calidad.

models:
  - name: stg_badges
    columns:
      - name: user_id     # atributo/columna
        tests:
          - not_null
  - name: stg_posts_answers
    columns:
      - name: post_id
        tests:
          - unique
          - not_null
      - name: type
        tests:
          - accepted_values:
              values: ['answer']   # si existe un valor diferente a answer, el modelo se va a caer.
      - name: owner_user_id
        tests:
          - relationships:
              to: ref('stg_users')
              field: user_id
  - name: stg_posts_questions
    columns:
      - name: post_id
        tests:
          - unique
          - not_null
  - name: stg_users
    columns:
      - name: user_id
        tests:
          - not_null
